### ISSUE TITLE
run nnie mapper yolov3.cfg

### ISSUE THREAD

**Issue by lccui** [rinetd/nnie_mapper#1]
V100R001C003B0031805151500142770
begin net parsing....
end net parsing
begin prev optimizing....
Segmentation fault (core dumped)
(py27) lab@lab-pc:~/soft/HiSVP_PC_V1.1.0.7/tool/nnie1.1/linux/HiSVP_nnie_mapper_V1.1.0.7$ ./nnie_mapper yolov3-ship-2wk.cfg 
V100R001C003B0031805151500142770
begin net parsing....
end net parsing
begin prev optimizing....
end prev optimizing....
begin net quantalizing....

**********************************************************
ERROR: file: _inputEdges  line: 206
Number of edges expected should match the number of input names.

**********************************************************
ERROR: file: setUpDataDelta  line: 779
ERROR: RUN FAILURE in line 779. Return = 524309

**********************************************************
ERROR: file: forward  line: 972
ERROR: RUN FAILURE in line 972. Return = 524309

**********************************************************
ERROR: file: inferenceForward  line: 1068
ERROR: RUN FAILURE in line 1068. Return = 524309

**********************************************************
ERROR: file: compile  line: 614
ERROR: RUN FAILURE in line 614. Return = 524309

**********************************************************
ERROR: file: iFEPCompile  line: 114
ERROR: RUN FAILURE in line 114. Return = 524309

**********************************************************
ERROR: file: main  line: 120
ERROR: RUN FAILURE in line 120. Return = 524309

(py27) lab@lab-pc:~/soft/HiSVP_PC_V1.1.0.7/tool/nnie1.1/linux/HiSVP_nnie_mapper_V1.1.0.7$ ./nnie_mapper yolov3-ship-2wk-d2c2.cfg.cfg 
V100R001C003B0031805151500142770

**********************************************************
ERROR: file: main  line: 44
real path error, [yolov3-ship-2wk-d2c2.cfg.cfg]!

(py27) lab@lab-pc:~/soft/HiSVP_PC_V1.1.0.7/tool/nnie1.1/linux/HiSVP_nnie_mapper_V1.1.0.7$ ./nnie_mapper yolov3-ship-2wk-d2c2.cfg     
V100R001C003B0031805151500142770
begin net parsing....

**********************************************************
ERROR: file: parseInputDim  line: 424
input shape size is not equal to input name size!

**********************************************************
ERROR: file: parseInputParamOldVersion  line: 331
ERROR: RUN FAILURE in line 331. Return = 262148

**********************************************************
ERROR: file: parseModel  line: 11280
ERROR: RUN FAILURE in line 11280. Return = 262148

**********************************************************
ERROR: file: compile  line: 512
ERROR: RUN FAILURE in line 512. Return = 262148

**********************************************************
ERROR: file: iFEPCompile  line: 114
ERROR: RUN FAILURE in line 114. Return = 262148

**********************************************************
ERROR: file: main  line: 120
ERROR: RUN FAILURE in line 120. Return = 262148

(py27) lab@lab-pc:~/soft/HiSVP_PC_V1.1.0.7/tool/nnie1.1/linux/HiSVP_nnie_mapper_V1.1.0.7$ ./nnie_mapper yolov3-ship-2wk-d2c2.cfg
V100R001C003B0031805151500142770
begin net parsing....
end net parsing
begin prev optimizing....
end prev optimizing....
begin net quantalizing....

**********************************************************
ERROR: file: _inputEdges  line: 206
Number of edges expected should match the number of input names.

**********************************************************
ERROR: file: setUpDataDelta  line: 779
ERROR: RUN FAILURE in line 779. Return = 524309

**********************************************************
ERROR: file: forward  line: 972
ERROR: RUN FAILURE in line 972. Return = 524309

**********************************************************
ERROR: file: inferenceForward  line: 1068
ERROR: RUN FAILURE in line 1068. Return = 524309

**********************************************************
ERROR: file: compile  line: 614
ERROR: RUN FAILURE in line 614. Return = 524309

**********************************************************
ERROR: file: iFEPCompile  line: 114
ERROR: RUN FAILURE in line 114. Return = 524309

**********************************************************
ERROR: file: main  line: 120
ERROR: RUN FAILURE in line 120. Return = 524309

**Comment by rinetd** [comment]
You should check your mapper cfg file. There may be some syntax errors in it。
